#!/bin/sh
# /usr/src/reconnect 
# for Base HAT

gpio -g mode 26 out	#HAT_POWER_OFF
gpio -g mode 19 out	#W_DISABLE

gpio -g write 26 0
gpio -g write 19 0

while true; do

	ping -q -I ppp0 -c 1 8.8.8.8 -s 0 >/dev/null

	if [ $? -ne 0 ]; then
		echo "Connection down, reconnecting..."
		sudo pon
	fi
	
	sleep 10
done
