#!/bin/bash

# This file is part of TorBox, an easy to use anonymizing router based on Raspberry Pi.
# Copyright (C) 2022 Patrick Truffer
# Contact: anonym@torbox.ch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it is useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# DESCRIPTION
# This file add automatically or manually bridges to /etc/tor/torrc.
#
# SYNTAX
# ./bridges_add_old <bridge mode> <standalone>
#
# <bridge mode>: "UseBridges 1" for bridge mode on; everything else = bridge mode off
# <standalone>: 0 - bridges_add_old was executed as part of the activation process, when no bridges were found
#               1 - bridges_add_old was directly executed
#
###### SET VARIABLES ######
#
# SIZE OF THE MENU
#
# How many items do you have in the main menu?
NO_ITEMS=2
#
# How many lines are only for decoration and spaces?
NO_SPACER=2
#
#Set the the variables for the menu
MENU_WIDTH=80
MENU_WIDTH_REDUX=60
MENU_HEIGHT_25=25
MENU_HEIGHT_15=15
# MENU_HEIGHT should not exceed 26
MENU_HEIGHT=$((8+NO_ITEMS+NO_SPACER))
MENU_LIST_HEIGHT=$((NO_ITEMS+NO_SPACER))

#Colors
RED='\033[1;31m'
WHITE='\033[1;37m'
NOCOLOR='\033[0m'

#Other variables
TOR_GET_BRIDGES_URL="https://bridges.torproject.org"
TORRC="/etc/tor/torrc"
MODE_BRIDGES=$1
STANDALONE=$2
number_bridges=0
i=0

###########################
######## FUNCTIONS ########

#include lib
.  /home/torbox/torbox/lib/torbox.lib

###########################

clear
CHOICE=$(whiptail --cancel-button "Back" --title "TorBox v.0.5.1 - ADD BRIDGES MENU" --menu "Choose an option (ESC -> go back)" $MENU_HEIGHT $MENU_WIDTH $MENU_LIST_HEIGHT \
"==" "===============================================================" \
" 1" "Add one OBFS4 bridge automatically (one bridge every 24 hours)"  \
" 2" "Add OBFS4 bridges manually"  \
"==" "===============================================================" \
3>&1 1>&2 2>&3)

CHOICE=$(echo "$CHOICE" | tr -d ' ')
case "$CHOICE" in

  # Add bridges automatically
  1)
    clear
    INPUT=$(cat text/add-bridges-automatically-text)
    if (whiptail --title "TorBox - INFO" --yesno "$INPUT" $MENU_HEIGHT_15 $MENU_WIDTH); then
      online_check $TOR_GET_BRIDGES_URL 1 1
      if [ $OCHECK == 1 ]; then
        echo -e "${RED}[+] Trying to fetch a bridge... this may take some time, please wait!${NOCOLOR}"
        trap "bash bridges_add_old $MODE_BRIDGES $STANDALONE; exit 0" SIGINT
        echo " "
				(rm -r /tmp/captcha.*) 2> /dev/null
        if [ $CLEARNET_DECISSION == 1 ]; then
          if [ "$TOR_DNS" == "0" ]; then local_clearnet_dns_resolution_on; fi
          bridge_address=$(python3 bridges_get.py)
          if [ "$TOR_DNS" == "0" ]; then local_clearnet_dns_resolution_off; fi
        else
          bridge_address=$(python3 bridges_get.py --network=tor)
        fi
        if [ "$bridge_address" = "0" ]; then
          echo " "
          echo -e "${RED}[+] Sorry, I couldn't fetch a bridge! Please, try again later or add bridges manually!${NOCOLOR}"
          echo " "
          read -n 1 -s -r -p "Press any key to continue"
          clear
          exit 0
        else
          if grep -q "$bridge_address" $TORRC ; then
            echo " "
            echo -e "${WHITE}[!] We fetched a bridge, but it is already added!${NOCOLOR}"
            echo -e "${RED}[+] Sorry, I didn't found a new valid bridge! Please, try again later or add bridges manually!${NOCOLOR}"
            echo " "
            read -n 1 -s -r -p "Press any key to continue"
            clear
            exit 0
          else
            echo -e "${RED}[+] Found a valid bridge!${NOCOLOR}"
            if [ "$MODE_BRIDGES" = "UseBridges 1" ]; then
              bridge_address="$(<<< "$bridge_address" sed -e 's`obfs4`Bridge obfs4`g')"
              bridge_address=$(echo -e "$bridge_address\n")
            else
              bridge_address="$(<<< "$bridge_address" sed -e 's`obfs4`#Bridge obfs4`g')"
              bridge_address=$(echo -e "$bridge_address\n")
            fi
            echo -e "${RED}[+] Saving a valid bridge!${NOCOLOR}"
            echo ""
            printf %s"$bridge_address\n" | sudo tee -a $TORRC
            echo ""
            echo -e "${RED}[+] DONE!${NOCOLOR}"
            sleep 5
            clear
            if [ $STANDALONE = 1 ]; then
              activate_obfs4_bridges bridges_add_old
              exit 0
            fi
          fi
        fi
      else
        echo ""
        echo -e "${WHITE}[!] OH NO! - no connection to the bridge database :( ${NOCOLOR}"
        echo -e "${WHITE}[!] Can't fetch a bridge - ABORTING :( ${NOCOLOR}"
        echo " "
        read -n 1 -s -r -p "Press any key to continue"
        clear
        exit 0
      fi
    fi
  ;;

  # Add bridges manually
  2)
    clear
    whiptail --title "TorBox - INFO" --textbox text/add-bridges-manually-text $MENU_HEIGHT_25 $MENU_WIDTH
    number_bridges=$(whiptail --title "TorBox - INFO" --inputbox "\n\nHow many bridges do you like to add?" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
    if ! [[ "$number_bridges" =~ ^[0-9]+$  ]]; then
      trap "bash bridges_add_old $MODE_BRIDGES $STANDALONE; exit 0" EXIT
      echo ""
      echo -e "${WHITE}[!] I asked you for a number and you gave me... what??? ${NOCOLOR}"
      echo " "
      sleep 5
      exit 1
    fi
    if [ $number_bridges -gt 0 ]; then
      i=1
      while [ $i -le $number_bridges ]
      do
        bridge_address=$(whiptail --title "TorBox - INFO" --inputbox "\n\nInsert one bridge (something like:\nobfs4 xxx.xxx.xxx.xxx:xxxx cert=abcd.. iat-mode=0)" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
        bridge_address="$(<<< "$bridge_address" sed -e 's/[[:blank:]]*$//')"
        if [ -z "$bridge_address" ]; then
          trap "bash bridges_add_old $MODE_BRIDGES $STANDALONE; exit 0" EXIT
          exit 0
        fi
        if grep -q "$bridge_address" $TORRC ; then
          echo -e "${WHITE}[!] Bridge number $i is already added!${NOCOLOR}"
          sleep 3
          i=$((i+1))
        else
          if [ "$MODE_BRIDGES" = "UseBridges 1" ]; then
            bridge_address="Bridge $bridge_address"
          else
            bridge_address="#Bridge $bridge_address"
          fi
          echo -e "${RED}[+] Saved bridge number $i!${NOCOLOR}"
          (printf %s"$bridge_address\n" | sudo tee -a $TORRC) 2> /dev/null
          i=$((i+1))
        fi
      done
      sleep 5
      clear
      if [ $STANDALONE = 1 ]; then
        activate_obfs4_bridges bridges_add_old
        exit 0
      fi
    else
      exit 0
    fi
  ;;

  *)
    clear
    exit 0
esac

bash bridges_add_old
exit 0
