#!/bin/bash

# This file is part of TorBox, an easy to use anonymizing router based on Raspberry Pi.
# Copyright (C) 2019 Patrick Truffer
# Contact: anonym@torbox.ch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it is useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# DESCRIPTION
# This file add bridges to /etc/torrc. However, it is only suitable for 3-5 bridges, because the bridges have to entered one by one.
#
# SYNTAX
# ./bridges_add <bridge mode>
#
# <bridge mode>: "UseBridges 1" for bridge mode on; everything else = bridge mode off
#
###### SET VARIABLES ######
#
#Set the the variables for the menu
MENU_WIDTH=80
MENU_WIDTH_REDUX=60
#
#
# OTHER VARIABLES
TORRC="/etc/tor/torrc"
number_bridges=0

##############################

number_bridges=$(whiptail --title "TorBox - INFO" --inputbox "\n\nHow many bridges do you like to add?" 20 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
if [ $number_bridges > 0 ]; then
    i=1
    while [ $i -le $number_bridges ]
    do
        bridge_address=$(whiptail --title "TorBox - INFO" --inputbox "\n\nInsert one bridge (something like:\nobfs4 xxx.xxx.xxx.xxx.:xxxx cert=abcd.. iat-mode=0)" 20 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
        if [ "$MODE" = "UseBridges 1" ]; then
          bridge_address="Bridge $bridge_address"
        else
          bridge_address="#Bridge $bridge_address"
        fi
        sudo echo $bridge_address >> $TORRC
        i=$(( $i+1 ))
    done
else
        exit 0
fi
