#!/bin/bash

# This file is part of TorBox, an easy to use anonymizing router based on Raspberry Pi.
# Copyright (C) 2020 Patrick Truffer
# Contact: anonym@torbox.ch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it is useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# DESCRIPTION
# This file flushes all LOG-files in /var/log and ~/.bash_history.
#
# SYNTAX
# ./deactivating_bridge_relay
#
#
###### SET VARIABLES ######

#Colors
RED='\033[1;31m'
WHITE='\033[1;37m'
NOCOLOR='\033[0m'

#Other variables
TORRC="/etc/tor/torrc"

##############################

MODE_BR=$(grep "BridgeRelay" ${TORRC})

#The if clause below is necessary
if [ "$MODE_BR" = "BridgeRelay 1" ]; then
  echo -e "${RED}[+] Deactivating Bridge Relay Mode...${NOCOLOR}"
	sudo sed -i "s/^BridgeRelay/#BridgeRelay/g" ${TORRC}
	sudo sed -i "s/^ORPort/#ORPort/g" ${TORRC}
	sudo sed -i "s/^ExtORPort/#ExtORPort/g" ${TORRC}
	sudo sed -i "s/^ServerTransportPlugin/#ServerTransportPlugin/g" ${TORRC}
	sudo sed -i "s/^ServerTransportListenAddr/#ServerTransportListenAddr/g" ${TORRC}
	sudo sed -i "s/^ContactInfo/#ContactInfo/g" ${TORRC}
	sudo sed -i "s/^Nickname/#Nickname/g" ${TORRC}
	sleep 2
  ORPORT=$(grep "^ORPort" ${TORRC})
  OBFS4PORT=$(grep "^ServerTransportListenAddr" ${TORRC})
  sORPORT=$(cut -d ' ' -f2 <<< $ORPORT)
  sOBFS4PORT=$(cut -d ':' -f2 <<< $OBFS4PORT)
	echo -e "${RED}[+] Closing port ORPort $sORPORT and OBFS4Port $sOBFS4PORT${NOCOLOR}"
	sudo iptables -D INPUT -p tcp --dport $sORPORT -j ACCEPT
	sudo iptables -D INPUT -p tcp --dport $sOBFS4PORT -j ACCEPT
fi
