#!/bin/bash

# This file is part of TorBox, an easy to use anonymizing router based on Raspberry Pi.
# Copyright (C) 2019 Patrick Truffer
# Contact: anonym@torbox.ch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it is useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# DESCRIPTION
# This file flushes all LOG-files in /var/log and ~/.bash_history.
#
# SYNTAX
# ./erase_log
#
#

echo "[+] Erasing ALL LOG-files..."
for logs in `find /var/log -type f`; do
	echo "[+] Erasing $logs"
	sudo rm $logs
	sleep 1
done
echo "[+] Erasing .bash_history"
sudo rm ../.bash_history
sudo history -c
