#!/bin/bash
# shellcheck disable=SC2001,SC2064

# This file is part of TorBox, an easy to use anonymizing router based on Raspberry Pi.
# Copyright (C) 2023 Patrick Truffer
# Contact: anonym@torbox.ch
# Website: https://www.torbox.ch
# Github:  https://github.com/radio24/TorBox
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it is useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# DESCRIPTION
# This file, is only use once during the first start-up.
# The purpose is to configure some important settings before or TorBox is
# connecting the tor network (for example OBFS4, Tor Automatic Counteractions...)
#
# SYNTAX
# ./first_use <NUMBER> <SOURCE SCRIPT>
#
# Following NUMBERs are supported:
# 1 - Will completely remove pi (only for Raspbian OS).
# 2 - Will generate new unique SSH server keys.
# 3 - Will ask the source of the Internet, if OBFS4 bridges should be aktivated (and then unmask) and if TACA be activated.
#
# If SOURCE SCRIPT is empty, the default is menu
#
##### SET VARIABLES ######
#Set the the variables for the menu
MENU_WIDTH=80
MENU_WIDTH_REDUX=60
MENU_HEIGHT_25=25
MENU_HEIGHT_20=20
MENU_HEIGHT_15=15
MENU_HEIGHT_10=10

#Colors
RED='\033[1;31m'
WHITE='\033[1;37m'
NOCOLOR='\033[0m'

# Identify the Operation System
CHECK_OS="$(lsb_release -si)"
CHECK_OS="$(echo "$CHECK_OS" | tail -n1)"

# Other variables
TORRC="/etc/tor/torrc"
RUNFILE="run/torbox.run"
FRESHINSTALLED=$1
[ ! -z $2 ] && SOURCE_SCRIPT=$2 || SOURCE_SCRIPT=menu

##############################
######## FUNCTIONS ###########

#include lib
.  /home/torbox/torbox/lib/torbox.lib

# This function is used for the step 1 as a trap for q
# Syntax finish_bridge_start2 <DEFAULT_BRIDGE_SUPPORT>
# Used predefined variables: RED, NOCOLOR, TORRC
finish_bridge_start2()
{
	DEFAULT_BRIDGE_SUPPORT=$1
	trap
	if [ "$DEFAULT_BRIDGE_SUPPORT" = "1" ]; then
   	# Did tor with bridge-support start up?
		REPLY=""
		while true
		do
			read -r -p $'\e[1;37mDid you see \"Bootstrapped 100%: Done\" [Y/n]? -> \e[0m'
			# The following line is for the prompt to appear on a new line.
			if [[ $REPLY =~ ^[YyNn]$ ]] ; then
				echo
				echo
				break
			fi
		done
		if [[ $REPLY =~ ^[Yy]$ ]] ; then
			echo -e "${RED}[+] DONE! TorBox is ready to work! Be careful with using it!${NOCOLOR}"
			echo
			echo
			sleep 5
			trap "bash $SOURCE_SCRIPT; trap; exit 0" EXIT
			exit 0
		else
			clear
			whiptail --textbox text/first_use-not_working-text $MENU_HEIGHT_15 $MENU_WIDTH
			CHECK=$(grep "^#ReachableAddresses" ${TORRC})
			if [ -z ${CHECK} ] ; then
				sudo sed -i "s/^ReachableAddresses /#ReachableAddresses /g" ${TORRC}
			else
				sudo sed -i "s/^#ReachableAddresses /ReachableAddresses /g" ${TORRC}
			fi
			clear
			trap "bash menu-bridges; trap; exit 0" EXIT
			exit 0
		fi
	else
		exit 0
	fi
}

# This function is used for the main program as a trap for q
# Syntax finish_bridge_start1 <DEFAULT_BRIDGE_SUPPORT>
# Used predefined variables: RED, NOCOLOR, TORRC
finish_bridge_start1()
{
 DEFAULT_BRIDGE_SUPPORT=$1
 trap
 if [ "$DEFAULT_BRIDGE_SUPPORT" = "1" ]; then
   # Did tor with bridge-support start up?
   echo ""
 	 while true
 	 do
 		 read -r -p $'\e[1;37mDid you see \"Bootstrapped 100%: Done\" [Y/n]? -> \e[0m'
 		 # The following line is for the prompt to appear on a new line.
 		 if [[ $REPLY =~ ^[YyNn]$ ]] ; then
 			 echo
 			 echo
 			 break
 		 fi
 	 done
 	 if [[ $REPLY =~ ^[Yy]$ ]] ; then
 		 echo -e "${RED}[+] DONE! TorBox is ready to work! Be careful with using it!${NOCOLOR}"
 		 echo
 		 echo
 		 sleep 5
 		 trap "bash $SOURCE_SCRIPT; trap; exit 0" EXIT
 		 exit 0
 	 else
     INPUT=$(cat text/first_use-anti-firewall-text)
     if (whiptail --title "TorBox - FIRST START UP!" --no-button "SUB-MENU" --yes-button "ANTI-FIREWALL" --yesno "$INPUT" $MENU_HEIGHT_20 $MENU_WIDTH); then
			 CHECK=$(grep "^#ReachableAddresses" ${TORRC})
			 if [ -z ${CHECK} ] ; then
				 sudo sed -i "s/^ReachableAddresses /#ReachableAddresses /g" ${TORRC}
			 else
				 sudo sed -i "s/^#ReachableAddresses /ReachableAddresses /g" ${TORRC}
			 fi
       clear
       echo -e "${RED}[+] DONE! Checking progress - please be patient!${NOCOLOR}"
       echo -e "    Ignore any error messages, this can take minutes just wait..."
       echo -e "    At the end, you should see \"${WHITE}Bootstrapped 100%: Done${NOCOLOR}\"."
       echo -e "    You can leave the progress report by pressing q."
       echo ""
			 # shellcheck disable=SC2064
			 trap "finish_bridge_start2 $DEFAULT_BRIDGE_SUPPORT" SIGINT
			 stty intr q
       sudo systemctl restart tor &
       sudo tail -f -n 0 /var/log/tor/notices.log | sed -u 's#.*Bootstrapped 100% (done): Done#\x1b[97m&\x1b[0m#' | grep -v -e "You configured a non-loopback address" -e "opening log file" -e "Application request when we haven't" -e "Giving up. (waiting for circuit)" -e "New control connection opened from" -e "While fetching directory info, no running dirservers known"
			 stty intr ^c
		 else
			 clear
			 echo -e "${RED}[+] We are starting now the Countermeasure sub-menu${NOCOLOR}"
			 echo -e "${RED}[+] For more information see here: https://www.torbox.ch/?page_id=797${NOCOLOR}"
			 echo
			 echo
			 read -n 1 -s -r -p "Press any key to continue"
			 sudo sed -i "s/^FRESH_INSTALLED=.*/FRESH_INSTALLED=0/" ${RUNFILE}
			 trap "bash menu-bridges; trap; exit 0" EXIT
			 exit 0
		 fi
	 fi
 fi
}


######## PREPARATIONS ########
# Resetting
shopt -s checkwinsize

# Probabaly only under Ubuntu shell output line separator fails to get reset: https://superuser.com/questions/1650758/how-does-the-shell-output-line-separator-fail-to-get-reset
if [ "$CHECK_OS" == "Ubuntu" ]; then stty sane; fi
if [ -z "$FRESHINSTALLED" ]; then FRESHINSTALLED=$(grep "^FRESH_INSTALLED=.*" ${RUNFILE} | sed "s/.*=//g"); fi


######## MAIN ########
while [ $FRESHINSTALLED -gt 0 ]; do
  case $FRESHINSTALLED in

		# TorBox v.0.5.3: Is not needed anymore !!!
    1)
      clear
			sudo sed -i "s/^FRESH_INSTALLED=.*/FRESH_INSTALLED=3/" ${RUNFILE}
      # if [ -d "/home/ubuntu" ]; then
        # sudo killall systemd
        # sleep 5
        # sudo userdel -r ubuntu --> not needed anymore, is in 3) included
				# This will remove the anoying SSH warning during the log in (which is not valid)
				# sudo sed -i "/pi:x:1000:1000:,,,:\/home\/pi:\/bin\/bash/d" /etc/passwd
				# sudo sed -i "/^pi:/d" /etc/shadow
      # fi
			# DON'T REMOVE IT! This is necessary because of possible kernel updates
			echo -e "${WHITE}[+] Fresh installation detected - we will reboot TorBox!${NOCOLOR}"
      sleep 5
      sudo reboot
    ;;

    # This will generate new unique SSH server keys (only for images)
    2)
      clear
      sudo sed -i "s/^FRESH_INSTALLED=.*/FRESH_INSTALLED=3/" ${RUNFILE}
      echo -e "${WHITE}[+] First time starting your TorBox!${NOCOLOR}"
      echo -e "${WHITE}[+] Generating new unique SSH server keys for your TorBox installation!${NOCOLOR}"
      (sudo rm -r /etc/ssh/ssh_host_*) 2>/dev/null
      sudo ssh-keygen -A
      echo ""
      echo -e "${WHITE}[+] To take effect, you have to close and reopen all your SSH sessions.${NOCOLOR}"
      FRESHINSTALLED=3
      sleep 10
    ;;

    # This will ask the source of the Internet, if OBFS4 bridges should be aktivated (and then unmask) and if TACA should be activated.
    3)
			# If there is still a home directory / user called "ubuntu", then we will remove it.
			if [ -d "/home/ubuntu" ]; then
				sudo userdel -r ubuntu
			fi

			# Welcome screen and asking if the user wants to configure the new installed TorBox
      clear
      INPUT=$(cat text/first_use-welcome-text)
      if (whiptail --title "TorBox - FIRST START UP (scroll down!)" --scrolltext --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
        sleep 1
      else
        sudo sed -i "s/^FRESH_INSTALLED=.*/FRESH_INSTALLED=0/" ${RUNFILE}
        exit 0
      fi

			# NEW v.0.5.3: Implementation of optional randomization of the hostname to prevent ISPs to see the default
			INPUT=$(cat text/randomize_hostname-text)
			HOSTNAME=$(hostname)
			INPUT=$(sed "s/HOSTNAMEANKER/$HOSTNAME/g" <<< "$INPUT")
			if (whiptail --title "TorBox Installation on Raspberry Pi OS" --defaultno --yes-button "CHANGE!" --yesno "$INPUT" $MENU_HEIGHT_20 $MENU_WIDTH); then
				if (whiptail --title "TorBox Installation on Raspberry Pi OS" --no-button "SET HOSTNAME" --yes-button "RANDOMIZE HOSTNAME" --yesno "You can set a specific hostname or use a randomized one. Please choose..." $MENU_HEIGHT_10 $MENU_WIDTH); then
					# shellcheck disable=SC2002
					HOSTNAME=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 10 | head -n 1)
				else
					HOSTNAME=$(whiptail --title "TorBox Installation on Raspberry Pi OS" --inputbox "\nEnter the hostname:" $MENU_HEIGHT_10 $MENU_WIDTH_REDUX 3>&1 1>&2 2>&3)
					if [[ $HOSTNAME != *[0123456789ABCDEFGHIJKLMNOPQRSTUVWXZYabcdefghijklmnopqrstuvwxzy-]* ]]; then
						HOSTNAME=$(tr -dc 'a-zA-Z0-9' <<<$HOSTNAME)
					fi
					if ${#HOSTNAME} -gt 64 ; then
						HOSTNAME=$(head -c 64 <<<$HOSTNAME)
					fi
				fi
				clear
				echo -e "${RED}[+] Setting up the hostname...${NOCOLOR}"
				(sudo hostnamectl set-hostname "$HOSTNAME") 2>/dev/null
				sudo systemctl restart systemd-hostnamed
				if grep "127.0.1.1.*" /etc/hosts ; then
					(sudo sed -i "s/127.0.1.1.*/127.0.1.1\t$HOSTNAME/g" /etc/hosts) 2>/dev/null
				else
					(sudo sed -i "s/^::1/127.0.1.1\t$HOSTNAME\n::1/g" /etc/hosts) 2>/dev/null
				fi
				whiptail --title "TorBox - INFO" --msgbox "TorBox's hostname is now changed to $HOSTNAME\n\nYou have to log out and again log into your console to see the change." $MENU_HEIGHT_10 $MENU_WIDTH_REDUX
			fi

			# Will the user keep using the default configured firewall circumvention?
			INPUT=$(cat text/first_use-firewall-text)
			if (whiptail --title "TorBox - FIRST START UP!" --no-button "NO" --yes-button "YES" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
				sudo sed -i "s/^#ReachableAddresses /ReachableAddresses /g" ${TORRC}
			else
				sudo sed -i "s/^ReachableAddresses /#ReachableAddresses /g" ${TORRC}
			fi

			# Configuring the source of the Internet
    	check_interface_with_internet
    	CHOICE=$(whiptail --nocancel --title "TorBox v.0.5.2 - FIRST START UP!" --menu "From where is the Internet coming? (ESC -> don't change)" 16 $MENU_WIDTH 8 \
    	"==" "===============================================================" \
    	" 1" "Ethernet cable (eth0)                                      "$FLASH_ETH0 \
    	" 2" "Wireless network (through an USB adapter; wlan1)           "$FLASH_WLAN1 \
    	" 3" "Wireless network (through the onboard chip; wlan0)         "$FLASH_WLAN0 \
    	" 4" "Cellular, USB dongle or Tethering (Android) (ppp0; usb0)   "$FLASH_USB0 \
    	" 5" "USB ethernet adapter or Tethering (iOS) (eth1)             "$FLASH_ETH1 \
    	" 6" "Over a VPN connection (tun0)                               "$FLASH_TUN0 \
    	"==" "===============================================================" \
    	3>&1 1>&2 2>&3)

      # This will configure the origin of the Internet.
      CHOICE=$(echo "$CHOICE" | tr -d ' ')
      if [ ! -z "$CHOICE" ]; then
        if [[ $CHOICE -gt 0  && $CHOICE -lt 7 ]]; then
          CHOICE=$((CHOICE+4))
          ./menu $CHOICE
        fi
      fi
      # Ask for TACA support
      clear
      INPUT=$(cat text/first_use-TACA-text)
			if (whiptail --title "TorBox - FIRST START UP!" --no-button "NO" --yes-button "YES" --yesno "$INPUT" $MENU_HEIGHT_15 $MENU_WIDTH); then
				# To start TACA, notices.log has to be present
				(sudo -u debian-tor touch /var/log/tor/notices.log) 2>/dev/null
				(sudo chmod -R go-rwx /var/log/tor/notices.log) 2>/dev/null
				if [ ! -f log_check_config.py ]; then
					clear
					for ARGUMENT in $(seq 1 6) ; do
						echo -e "${RED}[+] Activating TorBox's automatic countermeasure - protection number $ARGUMENT${NOCOLOR}"
						sleep 1
						LOOP_NUMBER=$((LOOP_NUMBER+1))
						[ $LOOP_NUMBER = 1 ] && (cp install/log_check_config/header log_check_config.py) &>/dev/null
						[[ "$ARGUMENT" =~ [1-6] ]] && (cat install/log_check_config/00"${ARGUMENT}" >> log_check_config.py) &>/dev/null
					done
					(cat install/log_check_config/footer >> log_check_config.py) &>/dev/null
				fi
				(sudo sed -i "s/^LOGCHECK=.*/LOGCHECK=1/" /home/torbox/torbox/run/torbox.run) &>/dev/null
				sudo ./log_check.py &
				echo -e "${RED}[+] TorBox's automatic countermeasure feature is activated!${NOCOLOR}"
				sleep 2
			else
				sudo pkill -f "log_check.py"
	      (sudo rm log_check_config.py) &>/dev/null
	      (sudo find /var/log/tor/ | grep "automat" | xargs -d"\n" sudo rm) &>/dev/null
	      (sudo sed -i "s/^LOGCHECK=.*/LOGCHECK=0/" /home/torbox/torbox/run/torbox.run) &>/dev/null
	      sleep 1
      fi

			# NEW v.0.5.2 post-release
			# Synchronize time to avoid problems with bridges
			clear
			sudo timedatectl set-timezone UTC
			echo -e "${WHITE}[!] SYSTEM-TIME CHECK${NOCOLOR}"
			echo -e "${RED}[!] Tor needs a correctly synchronized time.${NOCOLOR}"
			echo -e "${RED}    The system should display the current UTC time:${NOCOLOR}"
			echo
			echo  "             Date: $(date '+%Y-%m-%d')"
			./clock.py
			echo
			echo -e "${RED}    You can find the correct time here: ${WHITE}https://time.is/UTC${NOCOLOR}"
			echo
			while true
			do
				read -r -p $'\e[1;31m    Do you want to adjust the system time [Y/n]? -> \e[0m'
				# The following line is for the prompt to appear on a new line.
				if [[ $REPLY =~ ^[YyNn]$ ]] ; then
					echo
					echo
					break
				fi
			done
			if [[ $REPLY =~ ^[Yy]$ ]] ; then
				settime
			fi
      # Ask for bridge support
			clear
      DEFAULT_BRIDGE_SUPPORT=0
      INPUT=$(cat text/first_use-add-bridges-text)
			if (whiptail --title "TorBox v.0.5.2 - FIRST START UP" --defaultno --no-button "NO" --yes-button "YES" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
				if grep "^ReachableAddresses" ${TORRC} ; then
					INPUT=$(cat text/no_antifirewall-please-text)
					if (whiptail --title "TorBox - INFO" --no-button "NO" --yes-button "DEACTIVATE IT!" --yesno "$INPUT" $MENU_HEIGHT_15 $MENU_WIDTH); then
						sudo sed -i "s/^ReachableAddresses /#ReachableAddresses /g" ${TORRC}
					fi
				fi
				if (whiptail --title "TorBox - INFO" --no-button "SNOWFLAKE" --yes-button "OBFS4" --yesno "Do you want to use OBFS4 or SNOWFLAKE bridges?" $MENU_HEIGHT_10 $MENU_WIDTH_REDUX); then
					sudo sed -i "s/^#UseBridges/UseBridges/g" ${TORRC}
					sudo sed -i "s/^#UpdateBridgesFromAuthority/UpdateBridgesFromAuthority/g" ${TORRC}
					sudo sed -i "s/^#ClientTransportPlugin meek_lite,obfs4/ClientTransportPlugin meek_lite,obfs4/g" ${TORRC}
					sudo sed -i "s/^ClientTransportPlugin snowflake /#ClientTransportPlugin snowflake /g" ${TORRC}
					sudo sed -i "s/^#Bridge obfs4 /Bridge obfs4 /g" ${TORRC}
					sudo sed -i "s/^Bridge snowflake /#Bridge snowflake /g" ${TORRC}
					sudo sed -i "s/^Bridge meek_lite /#Bridge meek_lite /g" ${TORRC}
				else
					sudo sed -i "s/^#UseBridges/UseBridges/g" ${TORRC}
					sudo sed -i "s/^#UpdateBridgesFromAuthority/UpdateBridgesFromAuthority/g" ${TORRC}
					sudo sed -i "s/^ClientTransportPlugin meek_lite,obfs4/#ClientTransportPlugin meek_lite,obfs4/g" ${TORRC}
					sudo sed -i "s/^#ClientTransportPlugin snowflake /ClientTransportPlugin snowflake /g" ${TORRC}
					sudo sed -i "s/^Bridge obfs4 /#Bridge obfs4 /g" ${TORRC}
					sudo sed -i "s/^Bridge meek_lite /#Bridge meek_lite /g" ${TORRC}
					clear
					sudo bash bridges_activate_snowflake norestart
				fi
	      DEFAULT_BRIDGE_SUPPORT=1
				clear
        echo -e "${RED}[+] Starting Tor ${WHITE}WITH${RED} bridge support...${NOCOLOR}"
        sleep 2
			else
				sudo sed -i "s/^UseBridges/#UseBridges/g" ${TORRC}
				sudo sed -i "s/^UpdateBridgesFromAuthority/#UpdateBridgesFromAuthority/g" ${TORRC}
				sudo sed -i "s/^ClientTransportPlugin meek_lite,obfs4/#ClientTransportPlugin meek_lite,obfs4/g" ${TORRC}
				sudo sed -i "s/^ClientTransportPlugin snowflake /#ClientTransportPlugin snowflake /g" ${TORRC}
				sudo sed -i "s/^Bridge obfs4 /#Bridge obfs4 /g" ${TORRC}
				sudo sed -i "s/^Bridge snowflake /#Bridge snowflake /g" ${TORRC}
				sudo sed -i "s/^Bridge meek_lite /#Bridge meek_lite /g" ${TORRC}
				DEFAULT_BRIDGE_SUPPORT=0
				clear
				echo -e "${RED}[+] Starting Tor ${WHITE}WITHOUT${RED} OBFS4 bridge support...${NOCOLOR}"
				sleep 2
			fi
      (sudo systemctl unmask tor) 2>/dev/null
			(sudo systemctl unmask tor@default.service) 2>/dev/null
      echo -e "${RED}[+] Unmasking Tor...${NOCOLOR}"
      sleep 2
      echo -e "${RED}[+] Enable Tor...${NOCOLOR}"
      (sudo systemctl enable tor) 2>/dev/null
      sleep 2
      echo -e "${RED}[+] Daemon reload...${NOCOLOR}"
      sudo systemctl daemon-reload
      sudo sed -i "s/^FRESH_INSTALLED=.*/FRESH_INSTALLED=0/" ${RUNFILE}
      FRESHINSTALLED=4
      sleep 5
      clear
      echo -e "${RED}[+] DONE! Checking progress - please be patient!${NOCOLOR}"
      echo -e "    Ignore any error messages, this can take minutes just wait..."
      echo -e "    At the end, you should see \"${WHITE}Bootstrapped 100%: Done${NOCOLOR}\"."
      echo -e "    You can leave the progress report by pressing q."
      echo ""
			# shellcheck disable=SC2064
      trap "finish_bridge_start1 $DEFAULT_BRIDGE_SUPPORT" SIGINT
			stty intr q
      sudo systemctl restart tor &
      sudo tail -f -n 0 /var/log/tor/notices.log | sed -u 's#.*Bootstrapped 100% (done): Done#\x1b[97m&\x1b[0m#' | grep -v -e "You configured a non-loopback address" -e "opening log file" -e "Application request when we haven't" -e "Giving up. (waiting for circuit)" -e "New control connection opened from" -e "While fetching directory info, no running dirservers known"
			stty intr ^c
    ;;

		# This will install additional network drivers
    4)
			clear
			INPUT=$(cat text/install_network_drivers-text)
			FRESHINSTALLED=0
			sudo sed -i "s/^FRESH_INSTALLED=.*/FRESH_INSTALLED=0/" ${RUNFILE}
			if (whiptail --title "TorBox v.0.5.2 - FIRST START UP" --yesno "$INPUT" $MENU_HEIGHT_20 $MENU_WIDTH); then
				bash install/install_network_drivers install
				recommended_reboot update
			fi
    ;;

    *) exit 1
  esac
done
