#!/bin/bash

# This file is part of TorBox, an easy to use anonymizing router based on Raspberry Pi.
# Copyright (C) 2019 Patrick Truffer
# Contact: anonym@torbox.ch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it is useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# DESCRIPTION
# This file restarts hostapd, check if the daemon is working and if not rests
# the configuration with the last working version and restarts the daemon again.
# Before hostapd is changed, you have to add the following line in the code:
# sudo cp ${HOSTAPD} ${HOSTAPD_SAV}
# This creates the backup file, which is needed by HOSTAPD="/etc/hostapd/hostapd.conf"
#
# SYNTAX
# nohup ./hostapd_fallback
#
#
##### SET VARIABLES ######
#
HOSTAPD="/etc/hostapd/hostapd.conf"
HOSTAPD_SAV="/etc/hostapd/hostapd.conf.tbx"


sudo service hostapd restart
sleep 5
LOG_STATUS=$(sudo systemctl is-active hostapd)
if [ $LOG_STATUS = activating ] || [ $LOG_STATUS = inactive ] ; then
	sudo cp ${HOSTAPD_SAV} ${HOSTAPD}
	sudo service hostapd restart
fi
