#!/bin/bash

# This file is part of TorBox, an easy to use anonymizing router based on Raspberry Pi.
# Copyright (C) 2019 Patrick Truffer
# Contact: anonym@torbox.ch
# Website: https://www.torbox.ch
# Github:  https://github.com/radio24/TorBox
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it is useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# DESCRIPTION
# This file saves the the current connection setting.
#
# SYNTAX
# ./save_connection
#
#
clear
if (whiptail --title "TorBox - INFO" --yesno "\n\nIf you save the current connection settings, TorBox will load them during next boot.\n\nWould you like to save the connection settings?" 15 60); then
	echo "[+] Save connection setting..."
  sudo sh -c "iptables-save > /etc/iptables.ipv4.nat"
  sleep 2
fi
