#!/bin/bash

# This file is part of TorBox, an easy to use anonymizing router based on Raspberry Pi.
# Copyright (C) 2020 Patrick Truffer
# Contact: anonym@torbox.ch
# Website: https://www.torbox.ch
# Github:  https://github.com/radio24/TorBox
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it is useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# DESCRIPTION
# This file sets all preconditions and defines all iptables rules to route the
# entire data stream from the connected clients (from two different interfaces) through the Tor network.
#
# SYNTAX
# ./set_interfaces_2 <outgoing interface> <incoming interface> <incoming interface> <captive portal>
#
# The <outgoing interface> is the door to the internet. Possible values for the <outgoing interface>:
# eth0  -> 	TorBox is connected to the internet with a cable (onboard ethernet interface).
# eth1  -> 	TorBox is connected to the internet with a tethering device.
# wlan0 ->  TorBox is connected to the internet through a wireless network (onboard WLAN chip).
# wlan1 -> 	TorBox is connected to the internet through a wireless network (USB WiFi adapter).
#	ppp0	->	TorBox is connected to the internet through a cellular adapter.
# usb0	->  TorBox is connected to the internet through a USB adapter.
#
# The <incoming interface> is where the client-device is connected to the TorBox. Possible values for the <incoming interface>:
# eth0  -> 	The device is connected with a cable (onboard ethernet interface).
# eth1	-> 	The device is connected with a cable (USB ethernet adapter).
# wlan0 -> 	The device is connected via wireless network (onboard WLAN chip).
# wlan1 -> 	The device is connected via wireless network (USB WiFi adapter).
#
# Possible values for <captive portal>:
# 0	->	The network connection is open -- no login/password/phone number etc. is required.
# 1	->	For a sucessful connection to the Internet login/password/phone number etc. is required (this is usually the case
#       with provider of free wireless network access in hotels, airports, Internet cafées etc.).
#
###### SET VARIABLES ######

#Colors
RED='\033[1;31m'
WHITE='\033[1;37m'
NOCOLOR='\033[0m'

#Other variables
MENU_WIDTH=80
MENU_WIDTH_REDUX=60
MENU_HEIGHT_25=25
MENU_HEIGHT_15=15
IPTABLES="/sbin/iptables"
MODPROBE="/sbin/modprobe"
WLAN_MANAGER="/usr/bin/wicd-curses"
WLAN_MANAGER_DAEMON_NAME="wicd"
MY_OWN_IP1="192.168.42.1"
MY_OWN_IP2="192.168.43.1"
INT_NET1="$MY_OWN_IP1/8"
INT_NET2="$MY_OWN_IP2/8"
O_DEVICE=$1
I_DEVICE1=$2
I_DEVICE2=$3
CAPTIVE=$4

###########################

###### WE WILL DEACTIVATE BRIDGE RELAY MODE FIRST ######
clear
sudo bash deactivating_bridge_relay

###### ADDITIONAL COMMANDS DEPENDED ON THE INTERFACE CONNECTED TO THE INTERNET ######
if [ "$O_DEVICE" = "eth0" ]; then
	if [ $CAPTIVE = 1 ]; then
		sudo bash set_captive_2 $O_DEVICE $I_DEVICE1 $I_DEVICE2
	fi
elif [ "$O_DEVICE" = "eth1" ]; then
	if [ $CAPTIVE = 1 ]; then
    sudo bash set_captive_2 $O_DEVICE $I_DEVICE1 $I_DEVICE2
	fi
elif [ "$O_DEVICE" = "wlan0" ]; then
	clear
	whiptail --title "TorBox - INFO (scroll down!)" --textbox text/wicd-text --scrolltext $MENU_HEIGHT_25 $MENU_WIDTH
	sudo sed -i "s/^wireless_interface = wlan1/wireless_interface = wlan0/" /etc/wicd/manager-settings.conf
	clear
	echo -e "${RED}[+] Waiting for the WLAN Manager...${NOCOLOR}"
	service $WLAN_MANAGER_DAEMON_NAME restart
	sleep 5
	$WLAN_MANAGER
	sudo sed -i "s/^wireless_interface = wlan0/wireless_interface = wlan1/" /etc/wicd/manager-settings.conf
	clear
	if [ $CAPTIVE = 1 ]; then
	   sudo bash set_captive_2 $O_DEVICE $I_DEVICE1 $I_DEVICE2
	fi
elif [ "$O_DEVICE" = "wlan1" ]; then
	clear
	whiptail --title "TorBox - INFO (scroll down!)" --textbox text/wicd-text --scrolltext $MENU_HEIGHT_25 $MENU_WIDTH
	sudo sed -i "s/^wireless_interface = wlan0/wireless_interface = wlan1/" /etc/wicd/manager-settings.conf
	clear
	echo -e "${RED}[+] Waiting for the WLAN Manager...${NOCOLOR}"
	service $WLAN_MANAGER_DAEMON_NAME restart
	sleep 5
	$WLAN_MANAGER
	clear
	if [ $CAPTIVE = 1 ]; then
	   sudo bash set_captive_2 $O_DEVICE $I_DEVICE1 $I_DEVICE2
	fi
fi

###### PREPARATIONS ######
clear
echo -e "${RED}[+] Flushing existing iptables rules...${NOCOLOR}"
$IPTABLES -F
$IPTABLES -F -t nat
$IPTABLES -X
$IPTABLES -P INPUT DROP
$IPTABLES -P OUTPUT ACCEPT
$IPTABLES -P FORWARD DROP
$MODPROBE ip_conntrack
$MODPROBE iptable_nat
$MODPROBE ip_conntrack_ftp
$MODPROBE ip_nat_ftp

###### INPUT chain ######
echo -e "${RED}[+] Setting up INPUT chain...${NOCOLOR}"
# State tracking rules
$IPTABLES -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
$IPTABLES -A INPUT -m state --state INVALID -j DROP
# Anti-spoofing rules
$IPTABLES -A INPUT -i $I_DEVICE1 ! -s $INT_NET1 -j LOG --log-prefix "SPOOFED PKT "
$IPTABLES -A INPUT -i $I_DEVICE2 ! -s $INT_NET2 -j LOG --log-prefix "SPOOFED PKT "
$IPTABLES -A INPUT -i $I_DEVICE1 ! -s $INT_NET1 -j DROP
$IPTABLES -A INPUT -i $I_DEVICE2 ! -s $INT_NET2 -j DROP
# Let packages to the localhost
$IPTABLES -A INPUT -i lo -j ACCEPT
# Open access from the internal network (usually my own devices)
$IPTABLES -A INPUT -i $I_DEVICE1 -j ACCEPT
$IPTABLES -A INPUT -i $I_DEVICE2 -j ACCEPT
# Allow ICMP Ping
$IPTABLES -A INPUT -p icmp --icmp-type echo-request -j ACCEPT
$IPTABLES -A INPUT -p icmp --icmp-type echo-reply -j ACCEPT

###### OUTPUT chain ######
echo -e "${RED}[+] Setting up OUTPUT chain...${NOCOLOR}"
# Avoid Linux kernel transproxy packet leak. See: https://lists.torproject.org/pipermail/tor-talk/2014-March/032507.html
$IPTABLES -A OUTPUT -m conntrack --ctstate INVALID -j DROP
$IPTABLES -A OUTPUT -m state --state INVALID -j DROP
#$IPTABLES -A OUTPUT ! -o lo ! -d 127.0.0.1 ! -s 127.0.0.1 -p tcp -m tcp --tcp-flags ACK,FIN ACK,FIN -j DROP    --> This rule slows the traffic down and blocks some tools
$IPTABLES -A OUTPUT ! -o lo ! -d 127.0.0.1 ! -s 127.0.0.1 -p tcp -m tcp --tcp-flags ACK,RST ACK,RST -j DROP
## I will be absolutely sure that no DNS requests are done outside Tor --> this will be visible in the log (but we don't block it yet)
$IPTABLES -A OUTPUT -o $O_DEVICE -p tcp --dport 53 -j LOG --log-prefix "SSH SHELL DNS-REQUEST TCP" --log-ip-options --log-tcp-options
$IPTABLES -A OUTPUT -o $O_DEVICE -p udp --dport 53 -j LOG --log-prefix "SSH SHELL DNS-REQUEST UDP" --log-ip-options
## No other restrictions for OUTPUT

###### FORWARD chain ######
echo -e "${RED}[+] Setting up FORWARD chain...${NOCOLOR}"
# State tracking rules
$IPTABLES -A FORWARD -m state --state INVALID -j DROP
# Allow ICMP Ping
$IPTABLES -A FORWARD -p icmp --icmp-type echo-request -j ACCEPT
$IPTABLES -A FORWARD -p icmp --icmp-type echo-reply -j ACCEPT

###### NAT rules ######
# Access on the box's own IP should be granted (only TCP)
$IPTABLES -t nat -A PREROUTING -i $I_DEVICE1 -d $MY_OWN_IP1 -p tcp -j REDIRECT
$IPTABLES -t nat -A PREROUTING -i $I_DEVICE2 -d $MY_OWN_IP2 -p tcp -j REDIRECT
# TCP/UDP/DNS over Tor
$IPTABLES -t nat -A PREROUTING -i $I_DEVICE1 -p tcp -j REDIRECT --to-ports 9040
$IPTABLES -t nat -A PREROUTING -i $I_DEVICE2 -p tcp -j REDIRECT --to-ports 9040
$IPTABLES -t nat -A PREROUTING -i $I_DEVICE1 -p udp --dport 53 -j REDIRECT --to-ports 9053
$IPTABLES -t nat -A PREROUTING -i $I_DEVICE2 -p udp --dport 53 -j REDIRECT --to-ports 9053
$IPTABLES -t nat -A PREROUTING -i $I_DEVICE1 -p udp -j REDIRECT --to-ports 9040
$IPTABLES -t nat -A PREROUTING -i $I_DEVICE2 -p udp -j REDIRECT --to-ports 9040
## Masquerading
$IPTABLES -t nat -A POSTROUTING -o $O_DEVICE -j MASQUERADE

###### FINISH ######
echo -e "${RED}[+] Restarting TOR...${NOCOLOR}"
sleep 5
sudo service tor restart
sleep 5
