#!/bin/bash

# This file is part of TorBox, an easy to use anonymizing router based on Raspberry Pi.
# Copyright (C) 2022 Patrick Truffer
# Contact: anonym@torbox.ch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it is useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# DESCRIPTION
# This file activates or deactivates Snowflake to circumvent censorship.
# Following variables can be used:
#
# SYNTAX
# ./snowflake <SNOWSTRING> <MEEKSTRING>
#
# <SNOWSTRING> <MEEKSTRING> give the status of Snowflake and Meek-Azure.
#
# Possible values for <SNOWSTRING> <MEEKSTRING>: "ON!" or "OFF".
#
#
##### SET VARIABLES ######
#
#Set the the variables for the menu
MENU_WIDTH=80
MENU_WIDTH_REDUX=60
MENU_HEIGHT_15=15
MENU_HEIGHT_25=25

#Colors
RED='\033[1;31m'
GREEN='\033[1;32m'
WHITE='\033[1;37m'
NOCOLOR='\033[0m'

#Other variables
BRIDGE_DB_URL="https://onionoo.torproject.org"
TORRC="/etc/tor/torrc"
RUNFILE="run/torbox.run"
SNOWSTRING=$1
MEEKSTRING=$2
EXITID=$(grep "^EXITID=" ${RUNFILE})
i=0

###########################
######## FUNCTIONS ########

#include lib
.  /home/torbox/torbox/lib/torbox.lib

######## PREPARATIONS ########
###########################

if [ $EXITID = "EXITID=1" ]; then
  sudo sed -i "s/^EXITID=.*/EXITID=0/" ${RUNFILE}
  exit 0
fi

case $SNOWSTRING in

	"OFF")
		clear
		if grep "^#ReachableAddresses" ${TORRC} ; then
			INPUT=$(cat text/no_antifirewall-please-text)
			if (whiptail --title "TorBox - INFO" --no-button "NO" --yes-button "DEACTIVATE IT!" --yesno "$INPUT" $MENU_HEIGHT_15 $MENU_WIDTH); then
				sudo sed -i "s/^ReachableAddresses /#ReachableAddresses /g" ${TORRC}
			fi
		fi
    clear
		echo -e "${WHITE}[!] SNOWFLAKE runs only with local clearnet DNS resolution!${NOCOLOR}"
		echo -e "${RED}[+] This is not a problem because all clients DNS resquests are still handled through Tor.${NOCOLOR}"
		echo ""
		local_clearnet_dns_resolution_on
		trap "bash snowflake; exit 0" SIGINT
		echo -e "${WHITE}[!] Let's check, if SNOWFLAKE could work for you!${NOCOLOR}"
		readarray -t configured_snowflake_deactivated < <(grep "^#Bridge snowflake " ${TORRC})
		if [ ${#configured_snowflake_deactivated[0]} = 0 ]; then
			echo " "
			echo -e "${WHITE}[!] There is no SNOWFLAKE configured! Did you change /etc/tor/torrc ?${NOCOLOR}"
			echo -e "${WHITE}[!] We cannot activate SNOWFLAKE! Contact anonym@torbox.ch for help!${NOCOLOR}"
			read -n 1 -s -r -p "Press any key to continue"
			exit 1
		else
			echo " "
			echo -e "${WHITE}[!] SNOWFLAKE is configured and ready!${NOCOLOR}"
			number_configured_snowflake_deactivated=${#configured_snowflake_deactivated[*]}
			sleep 5
		fi
		echo " "
		online_check $BRIDGE_DB_URL 1 1
		if [ $OCHECK == 1 ]; then
			echo " "
			echo -e "${WHITE}[+] OK - we are connected with the bridge database${NOCOLOR}"
			echo -e "${RED}[+] Checking next the SNOWFLAKE SERVER - this could take a moment!${NOCOLOR}"
			echo -e "${RED}[+] You can only use SNOWFLAKE, if the server is ONLINE!${NOCOLOR}"
			sleep 2
			echo " "
			SNOW_ON=0
			i=0
			while [ $i -lt $number_configured_snowflake_deactivated ]
			do
				bridge_address=$(cut -d ' ' -f3,4 <<< ${configured_snowflake_deactivated[$i]})
				bridge_hash=$(cut -d ' ' -f2 <<< $bridge_address)
				#Snowflake works only through clearnet
				bridge_status=$(./bridges_check.py -f $bridge_hash)
				case $bridge_status in
					0) bridge_status_txt="${RED}- OFFLINE${NOCOLOR}";;
					1)
						bridge_status_txt="${GREEN}- ONLINE${NOCOLOR}"
						SNOW_ON=$((SNOW_ON+1))
					;;
					2) bridge_status_txt="- DOESN'T EXIST";;
				esac
				i=$((i+1))
				bridge_address="$i : $bridge_address $bridge_status_txt"
				echo -e "$bridge_address"
			done
			if [ $SNOW_ON == 0 ] ; then
				echo " "
				echo -e "${WHITE}[!] SORRY! - the SNOWFLAKE SERVER seems to be OFFLINE!${NOCOLOR}"
				echo -e "${RED}[+] However, we will try to use it anyway!${NOCOLOR}"
			fi
			echo " "
			read -n 1 -s -r -p "Press any key to continue"
		else
			echo " "
			echo -e "${WHITE}[!] SORRY! - no connection with the bridge database!${NOCOLOR}"
			echo -e "${RED}[+] We cannot check the SNOWFLAKE SERVER. However, we will try to use it anyway!${NOCOLOR}"
			echo " "
			read -n 1 -s -r -p "Press any key to continue"
		fi
		clear
		INPUT=$(cat text/activate-snowflake-text)
		if (whiptail --title "TorBox - INFO (scroll down!)" --scrolltext --defaultno --no-button "NO" --yes-button "YES" --yesno "$INPUT" $MENU_HEIGHT_25 $MENU_WIDTH); then
			clear
			deactivating_bridge_relay
			deactivate_obfs4_bridges NORESTART
			sudo sed -i "s/^Bridge obfs4 /#Bridge obfs4 /g" ${TORRC}
			sudo sed -i "s/^Bridge meek_lite /#Bridge meek_lite /g" ${TORRC}
			sudo sed -i "s/^#UseBridges/UseBridges/g" ${TORRC}
			sudo sed -i "s/^#UpdateBridgesFromAuthority/UpdateBridgesFromAuthority/g" ${TORRC}
			sudo sed -i "s/^#ClientTransportPlugin snowflake/ClientTransportPlugin snowflake/g" ${TORRC}
			sudo sed -i "s/^#Bridge snowflake /Bridge snowflake /g" ${TORRC}
			sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
			clear
			restarting_tor snowflake
		fi
  ;;

	"ON!")
    INPUT=$(cat text/deactivate-snowflake-text)
    if (whiptail --title "TorBox - INFO" --defaultno --no-button "NO" --yes-button "YES" --yesno "$INPUT" $MENU_HEIGHT_15 $MENU_WIDTH_REDUX); then
      clear
      sudo sed -i "s/^Bridge snowflake /#Bridge snowflake /g" ${TORRC}
      sudo sed -i "s/^Bridge meek_lite /#Bridge meek_lite /g" ${TORRC}
      sudo sed -i "s/^UseBridges/#UseBridges/g" ${TORRC}
      sudo sed -i "s/^UpdateBridgesFromAuthority/#UpdateBridgesFromAuthority/g" ${TORRC}
      sudo sed -i "s/^ClientTransport/#ClientTransport/g" ${TORRC}
      sudo sed -i "s/^Bridge obfs4 /#Bridge obfs4 /g" ${TORRC}
      sudo sed -i "s/^EXITID=.*/EXITID=1/" ${RUNFILE}
			local_clearnet_dns_resolution_off
      restarting_tor snowflake
    fi
  ;;
esac
