#!/bin/bash

# This file is part of TorBox, an easy to use anonymizing router based on Raspberry Pi.
# Copyright (C) 2021 Patrick Truffer
# Contact: anonym@torbox.ch
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it is useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# DESCRIPTION
# This file installs network drivers provided on http://downloads.fars-robotics.net/wifi-drivers/
#
# SYNTAX
# ./install_network_driver
#
#
##### SET VARIABLES ######
#
#Colors
RED='\033[1;31m'
WHITE='\033[1;37m'
NOCOLOR='\033[0m'

##############################
######## FUNCTIONS ###########

# This function downloads, unpacks and installs the network drivers
# Syntax install_network_drivers <path> <filename> <text_message>
install_network_drivers()
{
	path=$1
  filename=$2
  text_message=$3
	clear
	cd ~
	mkdir install_network_driver
	cd install_network_driver
	echo -e "${RED}[+] Downloading $filename ${NOCOLOR}"
	wget http://downloads.fars-robotics.net/wifi-drivers/$path$filename
	echo -e "${RED}[+] Unpacking $filename ${NOCOLOR}"
	tar xzf $filename
	chmod a+x install.sh
	echo -e "${RED}[+] Installing the $text_message ${NOCOLOR}"
	sudo ./install.sh
	cd ~
	rm -r install_network_driver
	sleep 2
}


kernelversion=$(uname -rv | cut -d ' ' -f1-2 | tr '+' ' ' | tr '#' ' ' | sed -e "s/[[:space:]]\+/-/g")

path_8188eu="8188eu-drivers/"
filename_8188eu="8188eu-"$kernelversion".tar.gz"
text_filename_8188eu="Realtek RTL8188EU Wireless Network Driver"
install_network_drivers $path_8188eu $filename_8188eu $text_filename_8188eu

path_8188fu="8188fu-drivers/"
filename_8188fu="8188fu-"$kernelversion".tar.gz"
text_filename_8188fu="Realtek RTL8188FU Wireless Network Driver"
install_network_drivers $path_8188fu $filename_8188fu $text_filename_8188fu

path_8192eu="8192eu-drivers/"
filename_8192eu="8192eu-"$kernelversion".tar.gz"
text_filename_8192eu="Realtek RTL8192EU Wireless Network Driver"
install_network_drivers $path_8192eu $filename_8192eu $text_filename_8192eu

# Deactivated because no driver for new kernels available
#path_8192su="8192su-drivers/"
#filename_8192su="8192su-"$kernelversion".tar.gz"
#text_filename_8192su="Realtek RTL8192SU Wireless Network Driver"
#install_network_drivers $path_8192su $filename_8192su $text_filename_8192su

path_8812au="8812au-drivers/"
filename_8812au="8812au-"$kernelversion".tar.gz"
text_filename_8812au="Realtek RTL8812AU Wireless Network Driver"
install_network_drivers $path_8812au $filename_8812au $text_filename_8812au

path_8821cu="8821cu-drivers/"
filename_8821cu="8821cu-"$kernelversion".tar.gz"
text_filename_8821cu="Realtek RTL8821CU Wireless Network Driver"
install_network_drivers $path_8821cu $filename_8821cu $text_filename_8821cu

path_8822bu="8822bu-drivers/"
filename_8822bu="8822bu-"$kernelversion".tar.gz"
text_filename_8822bu="Realtek RTL8822BU Wireless Network Driver"
install_network_drivers $path_8822bu $filename_8822bu $text_filename_8822bu

# Deactivated because no driver for new kernels available
#path_mt7610="mt7610-drivers/"
#filename_mt7610="mt7610-"$kernelversion".tar.gz"
#text_filename_mt7610="Mediatek MT7610 Wireless Network Driver"
#install_network_drivers $path_mt7610 $filename_mt7610 $text_filename_mt7610

# Deactivated because no driver for new kernels available
#path_mt7612="mt7612-drivers/"
#filename_mt7612="mt7612-"$kernelversion".tar.gz"
#text_filename_mt7612="Mediatek MT7610 Wireless Network Driver"
#install_network_drivers $path_mt7612 $filename_mt7612 $text_filename_mt7612
