# Generated by Django 3.2.9 on 2021-12-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=24, null=True, unique=True)),
                ('nick', models.CharField(max_length=18, unique=True)),
                ('pub_key', models.TextField(unique=True)),
            ],
        ),
    ]
