# Generated by Django 4.0.6 on 2022-07-06 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_dir', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('size', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
                ('path', models.TextField()),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesharing.downloadfilemodel')),
            ],
        ),
    ]
